version: "3.2"

services:
  menu-api:
    container_name: menu-api
    image: menu_api
    build:
      context: ./ms-menu
    ports:
      - "8080:8080"       
    networks:
      - microservices-development-network
  menu-mongo-db:
    container_name: menu-mongo-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: menu
    ports:
      - "27017:27017"
    networks:
      - microservices-development-network  

networks:
  microservices-development-network:
    driver: bridge