version: "3.2"

services:
  menu_api:
    container_name: menu_api
    image: menu_api
    build:
      context: ./ms-menu
    ports:
      - "8080:8080"       

  menu_mongo_db:
    container_name: menu_mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: menu
    ports:
      - "27017:27017"
    volumes:
      - /home/dev/Docker/Volumes/MenuMongoDB:/data/db

  order_mongo_db:
    container_name: order_mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: order
    ports:
      - "27018:27017"
    volumes:
      - /home/dev/Docker/Volumes/OrderMongoDB:/data/db

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq